// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6noI34wt-64dY20WCa5WXhjrrLfTS9S4',
    appId: '1:274872998586:android:372fa66c09d78fd6848083',
    messagingSenderId: '274872998586',
    projectId: 'rechat-f121a',
    storageBucket: 'rechat-f121a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACZSt0l3ixEWM9ET0gp35Xmvq4huFEYps',
    appId: '1:274872998586:ios:a05171da9705e543848083',
    messagingSenderId: '274872998586',
    projectId: 'rechat-f121a',
    storageBucket: 'rechat-f121a.appspot.com',
    androidClientId: '274872998586-605cjf5bduikqn5mln0iifad94uhutkt.apps.googleusercontent.com',
    iosClientId: '274872998586-5qjb9qd1gf3vrnbmufkr2chh6puk7s07.apps.googleusercontent.com',
    iosBundleId: 'com.plic.rechat.rechat',
  );
}
